### ISSUE TITLE
Trend: change X axis resolution

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-chart-view#101]
In trend window, change the X axis to not necessarily aggregate by every month. Provide a UI for switching between “bucketing resolutions” of 12, 6, 3, and 1 months.

Both Trend charts should use the same X axis resolution.

This would literally start counting back from whatever month user has selected as the end date; not a fixed Jan-Mar quartering sort of deal.

**Comment by gregallensworth** [comment]
See the new `gda-issue101-trendx` branch, which may do just what they need.

![image](https://user-images.githubusercontent.com/3117633/46436264-491deb80-c70d-11e8-9ca7-e216425b1ebf.png)

![image](https://user-images.githubusercontent.com/3117633/46436289-53d88080-c70d-11e8-9c3e-3d2bf2c7d70c.png)

![image](https://user-images.githubusercontent.com/3117633/46436303-5e931580-c70d-11e8-87a4-6fc7f577e3d7.png)

![image](https://user-images.githubusercontent.com/3117633/46436329-6a7ed780-c70d-11e8-8858-0c6dc050e6ab.png)

**Comment by gregallensworth** [comment]
Toltip X position fix:

![image](https://user-images.githubusercontent.com/3117633/46438269-5093c380-c712-11e8-9b02-483d389dd26e.png)

**Comment by danrademacher** [comment]
I see based on chunks starting at the beginning of time going forward vs starting present and going back is why most current 2 months are always separate from the larger agg summarization:
![image](https://user-images.githubusercontent.com/1423200/46447225-7c747080-c735-11e8-86a6-fc0163107271.png)

If we have to start at the beginning, I wonder if we hard-code in a Jan 2012 start date, so at least fixed periods align with familiar calendar years, semiannual, quaters.

**Comment by gregallensworth** [comment]
I don't see any way around that fact, that if you want data divided into buckets of X then the number of data points should be divisible by X. At either the beginning or end, there will be a remainder when the number of months (currently 85) is not divisible by X.

The good news though, is that the blocks are labeled so it's clear when your block is not the right size: the most recent block is Aug-Sep 2018 which is clearly not 3 months.

But if it is preferable that this remainder be back in 2011 on grounds that it is "probably relevant less often", then it should be a small change to reverse the list and chunk it, then reverse it again. That should give us X-month blocks starting present and leaving the "undersized remainder" back in 2011.

**Comment by gregallensworth** [comment]
Tooltip behavior: If block size is `< X` then the tooltip explicitly states the length.

![image](https://user-images.githubusercontent.com/3117633/46488965-0c0f3300-c7b9-11e8-9406-352288f0b376.png)

**Comment by gregallensworth** [comment]
Chunking behavior: Starts at the present, works backward.

![image](https://user-images.githubusercontent.com/3117633/46489258-c69f3580-c7b9-11e8-8a56-3f5efa7892c5.png)

Commit dc57ab7 brings the first round of chunking behavior. But commit e77b006 changes the plotting position of a block on the chart/timeline, as being the block's *ending date* This gives the more pleasant visual effect, that the Jul/Aug/Sep block now extends past July but not quite to Oct -- just what one would expect visually.

At the beginning of time, it looks like the screenshot below. The visibly drawn line starts at September, as that it the plotting point of the three-month aggregate.

![image](https://user-images.githubusercontent.com/3117633/46489421-34e3f800-c7ba-11e8-9db5-dff99baf0c46.png)

**Comment by gregallensworth** [comment]
One last UI item:

![image](https://user-images.githubusercontent.com/3117633/46499759-ca40b580-c7d5-11e8-85af-61b2dad269ef.png)


When the text of the tooltip is not sufficiently lengthy (e.g. with no comparison areas selected), **and also** one adds to the months readout "X months" wording, then the tooltip may not be wide enough to contain the text and it overflows.
