### ISSUE TITLE
Rank: add Borough field to other geogs + display here

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-chart-view#103]
The Intersections are special here, in that they have both a title and a subtitle: Borough & Intersection name.

They like this so much, that they want to apply this to the other geogs.

First order of business:
- [x] update datasets so there exists a *borough* field in these other tables
  - [x] Community Board
  - [x] NYPD Precinct
  - [x] NTA Neighborhood

**It would be important** that each area fits into exactly 1 borough. If they cross a boundary so a place can have >1 borough, that could make for some really goofy display readouts and new UI considerations.

Then, the UI update to show the Borough + place name like Intersections do.
- [x] Community Board
- [x] NYPD Precinct
- [x] NTA Neighborhood
- [x] but not Borough, of course

**Comment by danrademacher** [comment]
Per client, applies to all EXCEPT City Council, which cross boroughs and should be left out of this

**Comment by gregallensworth** [comment]
This is in place on a new branch `gda-issue103-boroughprefix` which we can merge in if we like it.

But I don't think it's everything they hope:

![image](https://user-images.githubusercontent.com/3117633/46379444-a35a7600-c653-11e8-91bb-54e7afa3c687.png)

The lists are drawn from all distinct *geo* names from the `crashes_prod_all` table, e.g. all distinct `nypc_precinct` values. As such, unlike a more well-thought system, the list does not reflect the set of all polygons known (making it independent of the crashes) but of all crashes found (making the list very dependent on the crashes table and only the crashes table).

You'll see that some options offered for neighborhood, et al have a blank borough. This is crashes which fall inside that precinct or neighborhood, but which fall outside a borough boundary, e.g. an edge case due where borders don't line up precisely.

Some options that come to mind:
* Ditch this endeavor, since it highlights data issues.
* Filter out crashes which have no borough set. This should be only a few out of a very large number.

**Comment by gregallensworth** [comment]
Dan says:  Let's go ahead and filter out crashes which have no borough. This should be very few by comparison.

**Comment by gregallensworth** [comment]
Comment https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/issues/103#issuecomment-426454608 done. When these borough-prefixed area types are used, crashes with a blank `borough` are omitted. This eliminates the need for a "No Borough" prefix.

Branch `gda-issue103-boroughprefix` should be ready for review.

**Comment by danrademacher** [comment]
This borough name add looks good. Merged master but not deployed yet. Will do that when we resolve the other two.
