### ISSUE TITLE
Mirror text changes from Mapper to Chart view

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#111]
Reference change over here: https://github.com/GreenInfo-Network/nyc-crash-mapper/issues/107

**Comment by gregallensworth** [comment]
- [ ] Copyright

- [ ] CRASHMAPPER Vehicle Filter to Help

- [ ] About, Enhanced Data paragraph

**Comment by gregallensworth** [comment]
These changes are in place in the `gda-vehtypefilter` branch.

Perhaps we should keep this issue open even after deployment, for the forthcoming vehicle filter video?

**Comment by danrademacher** [comment]
Drat, I missed two changes in her unmarked up About copy change. Asked for a highlight version after she said we missed some changes:
![image](https://user-images.githubusercontent.com/1423200/77476705-4834ba00-6dd8-11ea-9f4e-053f41e919df.png)

>The [LILY AUCHINCLOSS FOUNDATION](https://lilynyc.org/) generous grant helped to write the vehicular analysis modules. 
and add
>by Chris Henrick

**Comment by gregallensworth** [comment]
Done.
* LILY AUCHINCLOSS FOUNDATION
* Chris Henrick
