### ISSUE TITLE
About view & copy

### ISSUE THREAD

**Issue by clhenrick** [GreenInfo-Network/nyc-crash-mapper-chart-view#45]
Need to decide what and where to show the "about" copy. We could use a modal similar to the map, but maybe it makes more sense to put it in the chart area.

Needs design & copy update; copy should be similar to what's in the Map view modal.

**Comment by danrademacher** [comment]
New copy for both map and chart apps is in this gDoc:
https://docs.google.com/document/d/1BfkLNbAuxOyRJkOa8cD3OtmNg-CdEfylQujRxURCuDU/edit

I pulled all links out and enclosed them in square brackets to make the translation to HTML easier.

**Comment by danrademacher** [comment]
Let's keep is simple on style. What you have is good in terms of body copy, links, bullet lists.

Headers can just be similar to the headers in the side panel -- all caps, 500 weight. This is sized at `2.3rem`. Seems OK to me.

![image](https://user-images.githubusercontent.com/1423200/33143213-0dc50268-cf6e-11e7-8a84-04d18468a206.png)
