### ISSUE TITLE
Add "citywide" to Compare

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#58]
I suspect this will immediately become an enhancement... but for now it's a question.

From Christine:
>In compare, the filter by boundary should include “citywide” as an option 

I can see that this makes sense just in context of Compare. One geog and two periods, which implies nothing under "Select Areas". 

And pretty sure we'd have to special case it so the option is available only in Compare. 

Is there a simpler solution I might be missing?

**Comment by danrademacher** [comment]
New goal:

- [ ] Add citywide totals as a persistent item at the top of the Compare view.
- [ ] Omit circles from citywide
- [ ] Add NEW totals of Persons Killed and Persons Injured to all Compare blocks. (This will be a separate issue that I'll link to momentarily)

![image](https://user-images.githubusercontent.com/1423200/37549905-6dfe73d4-2942-11e8-82a4-9eb1d6f473fa.png)

**Comment by gregallensworth** [comment]
Working. Screenshot:

![image](https://user-images.githubusercontent.com/3117633/37617104-4ce3f5a0-2b6f-11e8-9394-ae5955b9bf8d.png)

**Comment by danrademacher** [comment]
Looked just right so I merged and deployed. For the record, I tested locally turning on circles for Citywide and as expected it nearly crashed my browser. Very slow. Noting here in case anyone later wants to add circles for citywide.
