### ISSUE TITLE
Ability to support custom-drawn areas

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-chart-view#62]
The main map allows one to draw custom polygonal areas and get statistics. To what degree would it be feasible, to pass these to the (separate) charting app, so as to compare two selected areas to this always-on "baseline"?

![image](https://user-images.githubusercontent.com/3117633/33632919-fb26da04-d9c3-11e7-9390-e16e3c263ddf.png)

Steps involved:
- [x] in the main map, have the Compare link include the `lngLats` URL param
- [x] on the charting app, accept `lngLats` URL param into the application state
- [x] on the charting app, a new Custom Area section as depicted above
  - [x] "Draw Area" will link to the main app, with the `&geo=custom` URL param so as to enable the drawing tool; the main app already has behavior per above, that the Compare link would contain their drawn area as URL params when they come back
  - [x]  "Clear Area" would empty the custom area, causing that line to disappear from the charting
- [x] on the Trend charting app, handling of this custom shape
  * this area is provided as a Benchmark Area
  * new SQL query exists to fetch the given area, and load it as the baseline comparison
- [x] on the Compare charting app, handling of this custom shape
  * this area occupies one of the two "selections", being the first of two
  * Select Areas would need wording changed to "select one" as the first area is already taken by the custom drawing

**Comment by danrademacher** [comment]
Note that links from the Map to chart views need to work both for "Compare" (as you outline above) and "Trend", which is the actual screenshot where I mocked in the new controls

**Comment by gregallensworth** [comment]
Progress per the above set of commits over the last day:

Trend seems to be up to the desired spec:

* accepts a latLngs param, loads this as a customGeography
* provides a new Custom Geography option in "Select a benchmark area"
* fetches and charts for the represented spatial area
* Clear Drawing button, erases the shape from memory and changes reference choice to citywide
* Draw button and Clear button, are reciprocal: only makes sense to clear a drawing which exists, and to draw one if none was given  ("Draw? I already drew it.")

**Comment by gregallensworth** [comment]
Dan reports problems when testing on his machine:

Hmm, when I run this locally and draw area, see charts for area, clear area, then click Draw Area again, the map loads but the data never does, with this in the console:
```
(index):1 POST https://chekpeds.carto.com/api/v1/map?stat_tag=API 400 (Bad Request)
index.js:178 Uncaught ["missing FROM-clause entry for table "a""]
```

I wonder if it involves unexpected or malformed URL params coming back to the map?

Here's the link I have:
```
http://localhost:8080/#/?cfat=false&cinj=true&clearCustomGeography&customGeography&endDate=2017-12&geo=custom&identifier=3&mfat=false&minj=true&pfat=false&pinj=true&setReferenceEntity=function%20%28%29%20%7B%0A%20%20%20%20return%20dispatch%28actionCreator.apply%28undefined%2C%20arguments%29%29%3B%0A%20%20%7D&startDate=2016-12
```
Seems like some of the stuff around  `setReferenceEntity` are somehow broken. I suspect some of these params just shouldn't be present for the map.

**Comment by clhenrick** [comment]
@gregallensworth why are you passing [all of these props](https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/blob/custom-area-charts/src/containers/FilterByCustomArea.jsx#L24-L29) to the main map's query params? Explains the junk in the link you posted above. 

The error:
```
(index):1 POST https://chekpeds.carto.com/api/v1/map?stat_tag=API 400 (Bad Request)
index.js:178 Uncaught ["missing FROM-clause entry for table "a""]
```
is coming from the `cartodbLayer.setSQL()` call from the map. Something in the query params is messing up the SQL query.

**Comment by clhenrick** [comment]
@gregallensworth my suspicion of what you're running into when you go from the chart view app to the map app via Draw Area is that currently the map app expects the `geo=custom` param to be accompanied by a list of lon lat coords. Not having that list is causing that SQL error from cartodb.js. 

You will have to alter the way custom area is handled on map load, making it flexible enough to load data without that list of lat lon coords, and to enable draw tools without the list as well. The places to do this are in the [constants/sql_queries](https://github.com/GreenInfo-Network/nyc-crash-mapper/blob/master/src/constants/sql_queries.js) and [LeafletMap](https://github.com/GreenInfo-Network/nyc-crash-mapper/blob/master/src/components/LeafletMap/index.js) modules in the map app. 

Hope that helps.

**Comment by danrademacher** [comment]
The goal here is to load the map with the Custom Area tool enabled, but no shape loaded. A bonus would be to maintain the time period queries for Period 1, but we could live without that.

So a link like this works:
http://crashmapper.org/#/?cfat=true&cinj=true&endDate=2017-11&geo=custom&identifier=&lat=40.702307691170844&lng=-73.8943327390625&lngLats=%255B%255D&mfat=true&minj=true&noInjFat=false&pfat=true&pinj=true&startDate=2015-11&zoom=11

We need to produce that sort of link from the chart app, knowing that some things (map center and zoom) can't be set dynamically from chart app.

I wonder if the code here, which makes the nav menu is useful reference?
https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/blob/master/src/containers/Menu.jsx#L33-L46

That's where we hard-code in center and zoom and then pull in other params.

**Comment by gregallensworth** [comment]
d67c477 adjusts `FilterByCustomArea` to send a minimal set of params: `startDate, endDate, geo=custom`

**Comment by clhenrick** [comment]
IMO it would make sense to abstract the logic linking to the map app so that it isn't duplicated in the `Menu` and `CustomArea` components. I'll stop commenting if this isn't helpful ;)

**Comment by danrademacher** [comment]
One thing I expect we'll hear from client is that if I draw a custom area, go to Trend or Compare and change nothing, then come back to map via main nav bar, I shouldn't lose my custom area. 

Flow like this:
![rwy2cw80av](https://user-images.githubusercontent.com/1423200/33844195-679c5d46-de54-11e7-9ded-d4a7af2a1ae1.gif)

Basically the "Map" link in nav would need to pass back the Custom Area if it is present. But maybe this is what was causing us trouble before?

**Comment by clhenrick** [comment]
Yes, the coords for the custom shape would have to be stored in the application state in the charting app. That way when toggling back to the map view to draw a shape the coords could be passed via query params.

The issue of the map view breaking after going to the map view from the chart view without having previously drawn a custom shape in the map view is slightly different. In this case the map app needs to be able to handle loading with the `geo=custom` flag and no coordinates for the custom shape. Currently it assumes that if it is loading with `geo=custom` that there is also a list of coordinates.

**Comment by gregallensworth** [comment]
The **Map** link now adds `geo=custom&lngLats=....` if a custom area exists in the state. Confirmed that the Map loads this drawing and filters to it (pre-existing behavior).

**Comment by danrademacher** [comment]
OK approval from client with one change:

Make "SELECT BENCHMARK AREA" read "SELECT A BENCHMARK OR CUSTOM AREA"

Then we're done

**Comment by gregallensworth** [comment]
Wording changed, adding "or custom"

**Comment by danrademacher** [comment]
verified and deployed

**Comment by danrademacher** [comment]
OK, and final step: 
- [ ] Merge branch with Master

**Comment by gregallensworth** [comment]
All merged, and the working branch was deleted.
