### ISSUE TITLE
Custom Area button remains active after it has been cleared

### ISSUE THREAD

**Issue by clhenrick** [GreenInfo-Network/nyc-crash-mapper-chart-view#65]
When the custom area has been cleared the "draw area" button shouldn't be in an active state. Looks like it defaults to an active state when the app loads with no query params / preloaded app state as well.

<img width="1440" alt="screen shot 2017-12-12 at 9 43 09 am" src="https://user-images.githubusercontent.com/161748/33899671-0a8c35ae-df21-11e7-8527-d56c7bf4beae.png">

**Comment by danrademacher** [comment]
Good point! But gonna have to call this an enhancement for now. Other irons in the fire with CHEKPEDS.

**Comment by clhenrick** [comment]
IMO more of a UI bug, but okay. Should be a simple fix.
