### ISSUE TITLE
Make reference default to Custom if a custom area is selected?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#66]
Follow on request from client after initial signoff on #62 

> if I map the custom area then click on “Trend” the custom area is properly selected adn the trend appears.  now If I use the selection pane, ( on the right) to  filter by  Borough,  the selection “custom area” disappears from the chart area and is replaced by “citywide” . I have to come back to the reference box in the main area and select “custom area” again.

Any idea what would be involved in forcing the BENCHMARK select to stay pinned to CUSTOM AREA if a custom area is active?

You can see the issue animated here:
![g3c4hdp4io](https://user-images.githubusercontent.com/1423200/33911600-bbd70dfe-df47-11e7-97b9-11f8e2f50ea7.gif)

Maybe some change to the Default Props here, https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/blob/dc9815fddf08a56e24814de13f628f33ef5554e4/src/containers/ReferenceEntitySelect.jsx#L28-L31. If Custom Area is present, default to that.

**Comment by gregallensworth** [comment]
To rephrase: Operating the **FILTER BY BOUNDARY** tool, seems to change the Benchmark area to *Citywide* *Can the tool not change the benchmark area, just leave it at prior selection?*

If done as stated above, that it will always force use of Custom Geography, that will invite a new complaint.
* Having selected Brooklyn as my benchmark, that option is de-selected in favor of Citywide -- and losing that in favor of Custom wouldn't be much better. The larger issue isn't Citywide vs Custom, but that the tool changes this setting.
* The ideal fix would be to have the current benchmark selection preserved.
* But acceptable secondary fix would be to use Custom or else Citywide, depending on whether a *customGeography* is in play.
