### ISSUE TITLE
Add Y axis labels to Trend?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#67]
Users are confused by double-axes on Trend. Can't get away from that, but what about “CUSTOM/BENCHMARK” on the right and “BOUNDARY” on the left. 

I assume then we need to modify code in this file, https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/blob/3100f60ff8cbe23da255decf2d19333e2766daf9/src/components/LineCharts/LineChart.jsx#L56, and probably some CSS to make this happen. Hard to know how feasible this is

**Comment by clhenrick** [comment]
Or you could add the actual name of the benchmark or custom area (e.g. Brooklyn) and the entity type (e.g. City Council) as well, as those are all stored in app state and could be passed down to the line chart. You'll need to up the padding on the left and right to accommodate the labels.

**Comment by danrademacher** [comment]
The actual name is a good idea if easy.

**Comment by gregallensworth** [comment]
Commit 4438ea9 brings this, and includes a lot of little details.

* Right-side axis is either reference or a secondary, and the axis text changes color accordingly.
* Area names use *Proper Title Case* to look nice, including Custom and Citywide.

![2017-12-13 13_13_34-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33962796-922fd66e-e007-11e7-9797-33cf96ff72a5.png)
![2017-12-13 13_13_55-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33962797-924d17c4-e007-11e7-84c2-2deee8d92089.png)

**Comment by danrademacher** [comment]
Per slack discussion, we're working on resolving confusion about left axis always for SELECT A BOUNDARY and right axis is always BENCHMARK/CUSTOM AREA

The left axis on Trend applies to BOTH selected Boundaries, and the right axis applies ONLY to Reference or Custom. So left axis could say “City Council” or “Borough” but not “District 3” or “Brooklyn”, while right axis could include any of the 6 values in the BENCHMARK/CUSTOM AREA menu.

Simplest:

1. Left axis is one of the values from the FILTER BY BOUNDARY select menu:

Borough
Community Board
City Council
Neighborhood (NTA)
NYPD Precinct

2. Right axis is one of the items in BENCHMARK/CUSTOM AREA select menu:

Citywide
Manhattan
The Bronx
Brooklyn
Queens
Staten Island
Custom Geography

**Comment by clhenrick** [comment]
Although it's somewhat redundant, it may be helpful to append "crashes" or "total crashes" to the labels on the y axis so that it's more clear to the user what is being displayed. I think that's typical of time series line chart: y-axis has a clear label of what the datum is being measured. So on the right could be "Custom Geography Total Crashes" and the left could be "City Council Total Crashes"; or maybe "Total Crashes: Custom Geography" and "Total Crashes: City Council".

**Comment by gregallensworth** [comment]
Here we go: reworked.

* Axes now read "Crashes per (districttype)" and "Crashes in (benchmark)"
  * except for Citywide, which says "Crashes Citywide" and not "Crashes in Citywide" :)


![2017-12-13 15_13_47-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33967701-6c126340-e019-11e7-9967-b7b6f096eee7.png)
![2017-12-13 15_21_33-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33967702-6c328e22-e019-11e7-8516-cd88c19fa7d8.png)
![2017-12-13 15_21_50-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33967703-6c4e4b94-e019-11e7-8b07-1682b41dc346.png)

**Comment by gregallensworth** [comment]
![2017-12-13 15_25_49-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33967831-ff263e86-e019-11e7-9aac-acf058b03c61.png)
![2017-12-13 15_26_10-nyc crash mapper](https://user-images.githubusercontent.com/3117633/33967832-ff41beea-e019-11e7-8d76-026e793196c4.png)
