### ISSUE TITLE
compare: select a <geo type> remains when custom area enabled

### ISSUE THREAD

**Issue by clhenrick** [GreenInfo-Network/nyc-crash-mapper-chart-view#69]
Seems like this is a side effect of implemting custom geo in compare & isn't intentional, as it's pushed to the very bottom. IMO seems worth removing if a custom geo is displayed.

![image](https://user-images.githubusercontent.com/161748/33923921-8a334146-df88-11e7-8d0e-b720db77c42b.png)

**Comment by danrademacher** [comment]
Still possible (and desired by client) to add 1 or 2 geogs to the UI to compare to the Custom Area. Perhaps the messaging could be a bit cleaner, but it'll have to do for now.
