### ISSUE TITLE
color specs for nav elements from client

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#75]
Speaking of detailed feedback... Christine says we still don't have consistent colors from Map to Chart views. I swear I had relented changed these back in the fall. Need to re- re-confirm.

For trend compare rank tabs: 
Title and top navigation fonts :  92,165,171
Background top nav and right nav: 110,110,110
Selections yellow tabs - 
not selected: 255,249,215
selected: 253, 203, 104
Yellow tabs fonts : 20,132,142 

For about tab
words with links : 92,165,171

Not at all about intersections, obv, but probably not hard to review and make 'em whatever colors she wants

**Comment by gregallensworth** [comment]
I went through and compared the color codes used in the top nav and yellow buttons, and confirmed that on the live CrashMapper and CrashMapper Chart pages, the color codes are identical. As such, we do already have "consistent colors from Map to Chart views"

I have made the color changes nonetheless on the Chart View, and screenshots are below. Many changes are quite subtle, with the background fill and About links being the most visually obvious.

* Top title + nav links
* Background color for timeline and sidebar
* Fill and text color, for sidebar yellow buttons; active state
* Fill and text color, for sidebar yellow buttons; inactive state
* About page, links within narrative text


### After changes
![after](https://user-images.githubusercontent.com/3117633/35340379-d158675c-00d7-11e8-9782-0c710f912d8c.png)

### Before changes  (From Live Site)

![before](https://user-images.githubusercontent.com/3117633/35340380-d17c8286-00d7-11e8-8a9a-452f649b0425.png)

**Comment by gregallensworth** [comment]
Per chat: The color codes between CrashMapper and CrashMapper Charts are already the same, and the new color codes are different than those currently in use on both sites. That's OK if she wants to change it in both sites, but let's bounce it back to the client to see if this is what she had in mind.

**Comment by danrademacher** [comment]
I finally understand what she's talking about. Sidebar vs sidebar on the live site (which doesn't have this change yet), and the chart sidebar is much lighter.

Here's a comparison with an easy fix. Left live vis is clearly lighter than right live map. Middle is closer to map.
![image](https://user-images.githubusercontent.com/1423200/35410146-41c0ddde-01c9-11e8-9e8a-a5129b99e470.png)

So her concern should be addressed if we leave all else the same as in live site but change `.grid-right` to
```css
.grid-right {
    background-color: rgba(0,0,0,.6);
}
```
