### ISSUE TITLE
Intersections data: EBBITTS STREET or EBBITTS AVENUE?

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-chart-view#79]
Noted while perusing the map: "EBBITTS AVENUE" is in the Intersections from LION, though the OSM basemap calls it "Ebbitts Street"

Which is correct? We can't correct the basemap, but could correct the intersection name.

![image](https://user-images.githubusercontent.com/3117633/35407054-7b6e481e-01bf-11e8-95b7-253ff80f7c18.png)

**Comment by danrademacher** [comment]
Client says don't worry about it.
