### ISSUE TITLE
Possible to add line breaks on rank card intersection names?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#85]
Client request:
>Ranking :could we start the intersection address on the next line so that borough is by itself on the first line? 

Like this:
![image](https://user-images.githubusercontent.com/1423200/35526393-1724ca66-04dc-11e8-93d7-7810383e0e27.png)

I imagine this will be a bit hacky, but maybe we could split on first comma or some such?

**Comment by gregallensworth** [comment]
Done in b868b1b

Small and simple change.
