### ISSUE TITLE
Why are the main navs so slightly different?

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#86]
Client has noted multiple times that the color and weight of nav is slightly different between the two apps. I just did yet another review of CSS and they look the same.

I thought it might be the variable map bg vs solid light gray creating that illusion.

But here;'s a test with same bg behind both:
![image](https://user-images.githubusercontent.com/1423200/35527093-702113a2-04de-11e8-8b14-9aa6dbc1572d.png)

the one on the left is darker. And yet both appear to be set to the same size, color, and transparency. 

Any idea what's going on here?

**Comment by gregallensworth** [comment]
Commit 87ea148 brings a workaround: increasing the opacity component of the RGBA code from 0.7 to 0.8 `rgba(23, 131, 143, .8)`

The CSS for them is indeed identical at every stage, and the containers don't have any opacity changes either. This could be some behavior within the browser and beyond the CSS, of trying to do color blending?

The workaround above gives the visual effect we're aiming for, though: the increased opacity gives the color a darker end result, visually.
