### ISSUE TITLE
Add Killed and Injured totals to compare

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#96]
Pulled out of #58 
Add NEW totals of Persons Killed and Persons Injured to all Compare blocks. (This will be a separate issue that I'll link to momentarily)

![image](https://user-images.githubusercontent.com/1423200/37549949-edc6078a-2942-11e8-8295-930a80ab392f.png)

**Comment by gregallensworth** [comment]
Done. Actual screenshot below.

![image](https://user-images.githubusercontent.com/3117633/37609899-84963a26-2b5b-11e8-8fdf-7b76e3ed8f9d.png)

**Comment by gregallensworth** [comment]
Confirmed to work with Custom Geography as well.

**Comment by gregallensworth** [comment]
Improvement: corrected for `NAN` results, if one disabled any of the crash filters. Prior behavior in 7ba82e3 did not account for `undefined` values for the missing values, should some of these filters be turned of.

![image](https://user-images.githubusercontent.com/3117633/37611171-dd5fd394-2b5e-11e8-99be-2f0356445d52.png)

**Comment by danrademacher** [comment]
Looked just right so I merged and deployed.
