### ISSUE TITLE
Client request for Compare layout changes

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#99]
Hmm, my attempt at minimal intervention Compare changes didn't fly entirely.

Revised proposed layout:
![image](https://user-images.githubusercontent.com/1423200/37855167-322064c6-2eab-11e8-8ceb-6d7a2a612939.png)

## Change list

- [x] Move date ranges to top of columns. Make `<h5>`. Don't repeat in each element.
- [x] Make Period A and Period B smaller type (`<h6>`) subhead below the date ranges.  Don't repeat in each element.
- [x] Turn the overall Killed and Injured tallies into 25% width centered columns to make them stand out
- [x] Add some new math to show % change from B to A, something like `(A - B)/B` to get a percentage. Set those below the values in Period A column, and set in about 12px font.

**Comment by gregallensworth** [comment]
Here we go:

![image](https://user-images.githubusercontent.com/3117633/37857962-c50c1ba2-2ebc-11e8-98c1-c9a52dd05da7.png)


Layout is as depicted above, *except* that per discussion: the killed & injured sums were shuffled a bit.
* The layout as given doesn't work so well on a 1024px-width display with large numbers, and will linewrap at 1024px width. A workaround would be using a smaller font (1.2rem), making the sums smaller than the surrounding text (1.4rem).
* This also has the visual effect of the numbers not being left-justified to surrounding content, "looks weird"

* Sums are not centered, instead being left-justified with some padding.
* Word "Persons" was removed from the sums, freeing up 16 characters of space and allowing regular font size to be used *and* for left-padding to justify the numbers above the words below.

Still to do: determine feasibility of comparing the two periods to create percentage diffs.

**Comment by gregallensworth** [comment]
Here are the percentage change readouts.

**Standard percentage change of A relative to B as a baseline**

Could display this on both; right now it is calculated but suppressed in Period B. Here for example, Period B's 3 fatalities versus 2 fatalities would be a "+50% change" relative to Period A. This would allow either one to be "the baseline" but also presumes that folks remember how  reciprocal fractions work.

<img width="548" alt="diffpercents" src="https://user-images.githubusercontent.com/3117633/37859018-902ec372-2eca-11e8-9beb-87feb54864eb.png">

**If a diff is under 1% then a special message is displayed.**

<img width="540" alt="under1percent" src="https://user-images.githubusercontent.com/3117633/37859019-904d9b6c-2eca-11e8-96aa-bbd78c628c8f.png">

**If the numbers are the same, NO CHANGE is displayed**
<img width="256" alt="nochange" src="https://user-images.githubusercontent.com/3117633/37859020-9070cbdc-2eca-11e8-8bdc-5ced1437028c.png">

**Comment by danrademacher** [comment]
Just deployed to live site

**Comment by danrademacher** [comment]
Client found an issue with Custom Area -- looks like when a Custom Area is drawn, its stats overwrite the Citywide:
![image](https://user-images.githubusercontent.com/1423200/38001655-d23489da-31e2-11e8-8be2-29dfea465c3d.png)

Citywide says 129 injured
[Link](
https://vis.crashmapper.org/?cfat=false&cinj=true&geo=city_council&lngLats=%255B%255B-73.99085998535155%252C40.65225269975945%255D%252C%255B-73.97747039794922%252C40.638185769935156%255D%252C%255B-74.00253295898438%252C40.63479884404164%255D%252C%255B-73.99085998535155%252C40.65225269975945%255D%255D&mfat=false&minj=true&p1end=2018-03&p1start=2017-03&p2end=2017-03&p2start=2016-03&pfat=false&pinj=true&primary&reference=custom&view=compare)

And same with Custom Area cleared:
![image](https://user-images.githubusercontent.com/1423200/38001675-e79de730-31e2-11e8-9e2a-9f4d682b8d2a.png)

Citywide 63,418 injured
[Link](https://vis.crashmapper.org/?cfat=false&cinj=true&geo=city_council&mfat=false&minj=true&p1end=2018-03&p1start=2017-03&p2end=2017-03&p2start=2016-03&pfat=false&pinj=true&primary&reference=citywide&view=compare)

**Comment by gregallensworth** [comment]
Here we go. I added a patch into the `DotGridSums` to force *citywide* for the Citywide section even if it is not our reference entity.

![image](https://user-images.githubusercontent.com/3117633/38264592-4f8ef63c-3728-11e8-8151-a0cee7366a7b.png)

**Comment by gregallensworth** [comment]
Closure of this Issue was accidental. Need to deploy and confirm on live site, before closing this.

**Comment by danrademacher** [comment]
Confirmed and deployed:
![image](https://user-images.githubusercontent.com/1423200/38265946-34876596-372c-11e8-96d5-23c7bc292511.png)
